services:
  backend:
    image: backend-api
    build: ./backend/
    restart: always
    ports:
      - 6601:6601
    deploy:
      mode: replicate
      replicas: 1


  postgres:
    image: postgres:14.0
    restart: always
    ports:
      - 6606:6606
    deploy:
      mode: replicate
      replicas: 1
    environment:
      POSTGRES_DB: chats
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
